[opt] navbar, sidebar-list, devicebar
xaoxuu/hexo-theme-stellar pull request #399
Opened 2024-03-02 05:47 UTC by L33Z22L11

- 美化侧边栏弹出按钮样式
  - 阴影颜色现在和文本颜色相同，而不是鲜艳的主题色
  - 高亮(active)的按钮现在具有半透明的背景色，而不是纯黑或者纯白
- 修复侧边栏最近文章列表的行高
  - 现在诸如`g` `y`等字符也能完整显示了，而不是底部被裁切
- 美化navbar中高亮(active)元素的样式
  - 侧边栏的导航栏中，图标底部的下划线具有和图标相同的颜色，而不是普通文本颜色
  - 略微增加了下划线的厚度，修正了border-radius值（应当是厚度的一半而不是厚度）
- 增加了页脚sitemap元素的圆角大小
  - 具有和主页顶部导航栏、超链接相同的值(4px)

2024-03-02 16:18 UTC, xaoxuu commented
谢谢提交代码，有些不太适合合并的我备注一下，大佬方便了修改一下

2024-03-03 10:55 UTC, L33Z22L11 commented
好的，期待 Rewiew

2024-03-27 02:58 UTC, xaoxuu requested changes

2024-03-27 02:58 UTC, xaoxuu commented on source/css/_common/device.styl
> +  box-shadow: 0 0 4px -1px var(--text-p4), 0 0 16px -4px var(--text-p4), 0 0 32px -12px var(--text-p4), 0 0 128px -32px var(--text-p4)
@L33Z22L11 这个按钮的风格修改建议自用吧

2024-03-27 02:58 UTC, xaoxuu commented on source/css/_common/device.styl
> +  background: var(--alpha75)
还有这个

2024-03-27 02:58 UTC, xaoxuu commented on source/css/_common/device.styl
> +  background: var(--alpha75)
还有这个

2024-03-27 02:58 UTC, xaoxuu commented on source/css/_layout/partial/navbar.styl
> +      height: 3px
我觉得3px有点厚了😅

2024-03-27 02:58 UTC, xaoxuu commented on source/css/_layout/sidebar/menu.styl
> +    min-height: 42px
搜索框和按钮高度都是40px

2024-03-27 02:58 UTC, xaoxuu commented on source/css/_layout/sidebar/menu.styl
> +      height: 3px
3px有点厚

2024-03-27 04:32 UTC, L33Z22L11 commented
已修改，请 Review

2024-03-27 06:16 UTC, merged