feat: add youtube video
xaoxuu/hexo-theme-stellar pull request #491
Opened 2024-06-12 11:22 UTC by Laitr0n

https://github.com/xaoxuu/hexo-theme-stellar/discussions/226#discussioncomment-9685505
 * 添加支持适配youtube的iframe嵌入 ，可设置最大宽度和是否自动播放

2024-06-12 12:05 UTC, xaoxuu approved these changes

2024-06-12 14:01 UTC, xaoxuu requested changes
有个冲突，麻烦处理一下

2024-06-12 15:29 UTC, L33Z22L11 commented on scripts/tags/lib/video.js
> +    <div class="tag-plugin video" style="aspect-ratio:${args.ratio || 16/9};max-width:${args.width};">
```
return
   `<div ...
```

字符串内部开头不要有空格，不然会在某些情况下解析为 Markdown 代码块语法。

2024-06-13 05:31 UTC, Laitr0n commented on scripts/tags/lib/video.js
> +    <div class="tag-plugin video" style="aspect-ratio:${args.ratio || 16/9};max-width:${args.width};">
Done.

2024-06-13 14:15 UTC, xaoxuu approved these changes

2024-06-13 14:15 UTC, merged

2024-06-13 14:16 UTC, xaoxuu commented
感谢大佬🤝

2024-06-13 14:47 UTC, Laitr0n commented
文档也需要更新一下。文档是否也开源？

2024-06-13 16:21 UTC, xaoxuu commented
是的